/usr/lib/python3.4/site-packages/deap/tools/_hypervolume/pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
Tipos: [1, 1, 1, 1, 1], rangos: [4, 2, 1, 1, 1]
--- Evolve in 120 possible combinations ---
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.4/multiprocessing/queues.py", line 362, in get
    return ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, 'm'.
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.4/multiprocessing/queues.py", line 360, in get
    res = self._reader.recv_bytes()
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 420, in _recv_bytes
    return self._recv(size)
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 383, in _recv
    chunk = read(handle, remaining)
MemoryError
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    ev.fit(scoring='accuracy', n_jobs=cpu_count(), kargs=searchParams)
  File "/home/Manuel.Castillo/pruebasOHC/lib/ProcessManager.py", line 36, in fit
    agcv.fit(self.X, self.y)
  File "./lib/easSearch.py", line 200, in fit
    self._fit(X, y, self.params)
  File "./lib/easSearch.py", line 263, in _fit
    halloffame=hof, verbose=self.verbose)
  File "/usr/lib/python3.4/site-packages/deap/algorithms.py", line 150, in eaSimple
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/util.py", line 252, in _run_finalizers
    finalizer()
  File "/usr/lib64/python3.4/multiprocessing/util.py", line 185, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 535, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib64/python3.4/multiprocessing/pool.py", line 522, in _help_stuff_finish
    inqueue._reader.recv()
  File "/usr/lib64/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
EOFError: Ran out of input
